<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        /*
            异常穿透：
                当使用Promise的then链式调用时，可以在最后指定失败的回调
                前面任何操作出现了异常，都会传到最后失败的回调中处理
        */
        let p = new Promise((resolve, reject) => {
            // resolve("OK");
            reject("err");
        });
        p.then(value => {
            throw "出错";
        }).then(value => {
            console.log(222); 
        }).catch(reason => {
            console.warn(reason); 
        })

    </script>
</body>
</html>