<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        /*
            await右侧的表达式一般为Promise对象,但也可以是其他的值
            如果表达式是Promise对象,await返回的是Promise成功的值
            如果表达式是其他值,直接将该值作为await的返回值

            注意:
                await必须写在async函数中,但async函数中可以没有await表达式
                如果await的Promise失败了,就会抛出异常,需要通过try...catch捕获处理
        */
        async function main(){
            let p = new Promise((resolve, reject) => {
                reject("err");
                // resolve("Ok");
            })

            // 1. 右侧是Promise
            // let res = await p;
            
            // 2. 右侧是其他值
            // let res = await 20;

            // 3. 右侧是失败的Promise
            try {
                let res = await p;
            } catch (error) {
                console.log(error);
            }

            console.log(res);
        }
        main();
    </script>
</body>
</html>